import React from 'react';
import Head from 'next/head';
import { WeatherApp } from '../components/weather-1';
/*
  Check for params. If weather1, weather2 or weather3, then set specific app in carousel.
*/
export default function Home() {
  return (
    <div className='container flex justify-center items-center'>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WeatherApp />
    </div>
  );
}
