import Head from 'next/head'
/*
  Check for params. If weather1, weather2 or weather3, then set specific app in carousel.
*/
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='flex flex-col'>
          <div className='flex p-4 justify-center items-center'>HAHA</div>
          <div className='flex p-4 justify-center items-center'>HAHA</div>
          <div className='flex p-4 justify-center items-center'>HAHA</div>
        </div>
      </main>
    </div>
  )
}
